version: '3.9'

services:
  server:
    build:
      context: ./birchwood-server/server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - my-network

  blog:
    build:
      context:  ./birchwood-blog
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - my-network

networks:
  my-network:

