version: "3.9"

services:
  server:
    build:
      context: ./birchwood-server/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
    networks:
      - my-network

  blog:
    build:
      context: ./birchwood-blog
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - my-network

  cms:
    build:
      context: ./birchwood-CMS
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - my-network

  mongodb:
    image: mongo:birchwood-1
    ports:
      - "27017:27017"
    volumes:
      - dbdata6:/data/db
    networks:
      - my-network

volumes:
  dbdata6:

networks:
  my-network:
    driver: bridge
